#!/bin/sh
Service_Start()
{
	isRunning=`ps aux |grep yunclient|grep 'www'`
	if [ "${isRunning}" != "" ];then
		Service_Stop
	fi
		
	#Service_Admin stop
	service mysqld stop
	pkill -9 pure-ftpd
	if [ -f "/var/run/pure-ftpd.pid" ];then
		rm -f /var/run/pure-ftpd.pid
	fi
	pkill -9 mysqld
	rm -f /www/server/data/*.pid
	pkill -9 nginx
	rm -f /www/server/nginx/logs/nginx.pid;
	pkill -9 httpd
	pkill -9 php-cgi
	
	rm -f /tmp/php-cgi-*
	if [ -f "/tmp/cloud.sock" ];then
		rm -f /tmp/cloud.sock
	fi
	nohup /www/server/cloud/yunclient >> /www/server/cloud/logs.pl 2>&1 &
	
	if [ -f '/var/lock/subsys/mysql' ];then
		rm -f /var/lock/subsys/mysql
	fi
	Service_Admin start
	echo -e "Service Yunclient Running			\033[32m[OK]\033[0m"
}

Service_Start_Centos7()
{
	if [ -f "/tmp/cloud.sock" ];then
		rm -f /tmp/cloud.sock
	fi
	nohup /www/server/cloud/yunclient >> /www/server/cloud/logs.pl 2>&1 &
}

Service_Admin()
{
	
	
	echo "======================================="
	if [ -f '/etc/init.d/nginx' ];then
		service nginx $1
	fi
	if [ -f '/etc/init.d/httpd' ];then
		service httpd $1
	fi
	if [ -f '/etc/init.d/pure-ftpd' ];then
        	service pure-ftpd $1
	fi
	if [ -f '/etc/init.d/mysqld' ];then
        	service mysqld $1
	fi
	if [ -f '/etc/init.d/php-fpm-52' ];then
        service php-fpm-52 $1
	fi
	if [ -f '/etc/init.d/php-fpm-53' ];then
		service php-fpm-53 $1
	fi
	if [ -f '/etc/init.d/php-fpm-54' ];then
		service php-fpm-54 $1
	fi
	if [ -f '/etc/init.d/php-fpm-55' ];then
		service php-fpm-55 $1
	fi
	if [ -f '/etc/init.d/php-fpm-56' ];then
		service php-fpm-56 $1
	fi
	if [ -f '/etc/init.d/php-fpm-70' ];then
		pid='/www/server/php/70/var/run/php-fpm.pid'
		if [ -f "${pid}" ];then
			rm -f $pid
		fi
		service php-fpm-70 $1
	fi
	if [ -f '/etc/init.d/php-fpm-71' ];then
		pid='/www/server/php/71/var/run/php-fpm.pid'
		if [ -f "${pid}" ];then
			rm -f $pid
		fi
		service php-fpm-71 $1
	fi
	echo "======================================="
}

Service_Stop()
{
	pid=`ps aux | grep yunclient |grep 'www'|awk '{print $2}'`
	kill -9 $pid
	if [ -f "/tmp/cloud.sock" ];then
		rm -f /tmp/cloud.sock
	fi
	echo -e "Service Yunclient Stoped 			\033[32m[OK]\033[0m"
}

Service_Restart()
{
	Service_Stop
	Service_Start
}

case $1 in
        'start') Service_Start
        ;;
        'stop') Service_Stop
        ;;
        'restart') Service_Restart
        ;;
		'c7start') Service_Start_Centos7
        ;;
        *) echo "Option {start|stop|restart}"
        ;;
esac

