#!/bin/sh
Service_Start()
{
	isRunning=`ps aux |grep slemp|grep 'www'`
	if [ "${isRunning}" != "" ];then
		Service_Stop
	fi

	#Service_Admin stop
	service mysql stop
	pkill -9 mysql
	rm -f /www/server/data/*.pid
	pkill -9 nginx
	rm -f /www/server/nginx/logs/nginx.pid;
	pkill -9 php-cgi
	pkill -9 php-fpm

	rm -f /tmp/php-cgi-*
	if [ -f "/tmp/cloud.sock" ];then
		rm -f /tmp/cloud.sock
	fi
	nohup /www/server/cloud/slemp >> /www/server/cloud/logs.pl 2>&1 &

	if [ -f '/var/lock/subsys/mysql' ];then
		rm -f /var/lock/subsys/mysql
	fi
	Service_Admin start
	echo -e "Service Panel Running			\033[32m[OK]\033[0m"
}

Service_Admin()
{


	echo "======================================="
	if [ -f '/etc/init.d/nginx' ];then
		service nginx $1
	fi
	if [ -f '/etc/init.d/mysql' ];then
        	service mysql $1
	fi
	if [ -f '/etc/init.d/php-fpm-54' ];then
		service php-fpm-54 $1
	fi
	if [ -f '/etc/init.d/php-fpm-55' ];then
		service php-fpm-55 $1
	fi
	if [ -f '/etc/init.d/php-fpm-56' ];then
		service php-fpm-56 $1
	fi
	if [ -f '/etc/init.d/php-fpm-70' ];then
		service php-fpm-70 $1
	fi
	if [ -f '/etc/init.d/php-fpm-71' ];then
		service php-fpm-71 $1
	fi
	if [ -f '/etc/init.d/php-fpm-72' ];then
		service php-fpm-72 $1
	fi
	if [ -f '/etc/init.d/php-fpm-73' ];then
		service php-fpm-73 $1
	fi
	echo "======================================="
}

Service_Stop()
{
	pid=`ps aux | grep slemp |grep 'www'|awk '{print $2}'`
	kill -9 $pid
	if [ -f "/tmp/cloud.sock" ];then
		rm -f /tmp/cloud.sock
	fi
	echo -e "Service Panel Stoped 			\033[32m[OK]\033[0m"
}

Service_Restart()
{
	Service_Stop
	Service_Start
}

case $1 in
        'start') Service_Start
        ;;
        'stop') Service_Stop
        ;;
        'restart') Service_Restart
        ;;
        *) echo "Option {start|stop|restart}"
        ;;
esac
